from __future__ import annotations

import ast
from pathlib import Path
from typing import Iterable


SOURCE_KEYWORDS = (
    "secret",
    "token",
    "password",
    "passwd",
    "api_key",
    "credential",
    "private_key",
)

EXCLUDED_HINTS = (
    "non_secret",
    "safe",
    "mask",
    "redact",
    "hash",
    "sanitize",
)

SCAN_ROOTS = (Path("app"), Path("benchmarks"))
OUTPUT_PATH = Path("stubs/taint/secrets_to_logs/generated_models.pysa")


def module_name_from_path(path: Path, root: Path) -> str:
    relative_path = path.relative_to(root).with_suffix("")
    return ".".join(relative_path.parts)


def is_suspicious(name: str) -> bool:
    lowered_name = name.lower()
    return any(keyword in lowered_name for keyword in SOURCE_KEYWORDS) and not any(
        excluded_hint in lowered_name for excluded_hint in EXCLUDED_HINTS
    )


def collect_function_models(tree: ast.AST, module_name: str) -> list[str]:
    models: list[str] = []

    def visit_body(body: Iterable[ast.stmt], class_prefix: tuple[str, ...] = ()) -> None:
        for node in body:
            if isinstance(node, ast.ClassDef):
                visit_body(node.body, class_prefix + (node.name,))
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if is_suspicious(node.name):
                    qualified_name = ".".join((module_name, *class_prefix, node.name))
                    models.append(f"def {qualified_name}() -> TaintSource[Secret]: ...")

    if isinstance(tree, ast.Module):
        visit_body(tree.body)

    return models


def scan_roots(roots: Iterable[Path]) -> list[str]:
    generated_models: set[str] = set()

    for root in roots:
        if not root.exists():
            continue

        for path in sorted(root.rglob("*.py")):
            if path.name == "__init__.py":
                continue

            module_name = module_name_from_path(path, root)
            tree = ast.parse(path.read_text(), filename=str(path))

            for model in collect_function_models(tree, module_name):
                generated_models.add(model)

    return sorted(generated_models)


def write_models(models: list[str], output_path: Path = OUTPUT_PATH) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    header = [
        "# Auto-generated by generate_models.py. Do not edit manually.",
        "# Source-like function names are modeled as Secret taint sources.",
        "",
    ]
    body = models if models else ["# No suspicious source functions were found."]
    output_path.write_text("\n".join(header + body) + "\n")


def main() -> None:
    models = scan_roots(SCAN_ROOTS)
    write_models(models)

    print(f"Wrote {len(models)} generated source model(s) to {OUTPUT_PATH}")
    for model in models:
        print(model)


if __name__ == "__main__":
    main()